config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', passwords: 'users/passwords'}
  root to: 'users#index'

  devise_scope :user do 
    get '/users/sign_out', to: 'users/sessions#destroy'
  end

  post '/api/v1/signup', to: 'api/v1/registrations#create'
  post '/api/v1/signin', to: 'api/v1/sessions#create'

  resources :posts, only: [:new, :create]
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :destroy] do
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create]
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show] do
        resources :posts, only: [:index, :show] do
          resources :comments, only: [:index, :show, :create]
        end
      end
    end
  end
end

# hello

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #  , :confirmable

  has_many :posts, foreign_key: 'author_id', class_name: 'Post', dependent: :delete_all
  has_many :likes, foreign_key: 'author_id', class_name: 'Like', dependent: :delete_all
  has_many :comments, foreign_key: 'author_id', class_name: 'Comment', dependent: :delete_all

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def most_recent_posts
    posts.limit(3).order(created_at: :desc)
  end

  def admin?
    return true if role == 'admin'

    false
  end

  def correct_token?(token)
    return true if apitoken == token

    false
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    return unless @current_user.present?

    users = User.all
    render json: users, status: :ok
  end

  def show
    user = User.find(params[:id])
    render json: user, status: :ok
  rescue StandardError => e
    render json: { error: e }, status: :not_found
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  skip_before_action :check_user
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :check_user
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  skip_before_action :check_user
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  skip_before_action :check_user
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  skip_before_action :check_user
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  skip_before_action :check_user
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :check_user
  load_and_authorize_resource

  def index
    @users = User.all
    @current_user = current_user
  end

  def show
    @user = User.includes(:posts).find(params[:id])
  end

  helper_method :asd
end

app/views/users/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Blog App!</title>
</head>
<body>
  <div class="index">
    <% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: "#{name} generic-alert" %>
    <% end -%>

    <div class="header black-border">
      <h2>Current User: <%= @current_user.name %></h2>
      <%= link_to 'Create Post', new_post_path, class: 'posts-btn black-border header-btn' %>
    </div>
    <% @users.each do |user| %>
      <div class="user">
        
        <img class="user-image black-border" src='<%= user.photo %>' alt="user-image">

        <div class="user-basic-data black-border">
          <%= link_to user.name, user_path(id: user.id), class: 'user-index-name hover-title' %>
          <p class="user-index-posts">Posts: <%= user.posts_counter || 0%></p>
        </div>
      </div>
    <% end %>
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  </div>
</body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Blog App! - User <%= @user.name %></title>
</head>

<body>
  <div class="index">
    <% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: "#{name} generic-alert" %>
    <% end -%>

    <div class="user">
      <img class="user-image black-border" src='<%= @user.photo %>' alt="user-image">
      <div class="user-basic-data black-border">
        <%= link_to @user.name, user_path(id: @user.id), class: 'user-index-name' %>
          <p class="user-index-posts">Posts: <%= @user.posts_counter || 0 %></p>
      </div>
    </div>

    <div class="user-bio black-border">
      <strong class="section-title">Bio</strong>
      <p><%= @user.bio %></p>
    </div>

    <div class="user-posts">
      <% @user.most_recent_posts.each do |post| %>
        <div class="user-post black-border">
          <%= link_to post.title, user_post_path(user_id: post.author.id,id: post.id), class: 'section-title' %>
          <p><%= post.reduced_text %></p>
          <p class="post-com-like">Comments: <%= post.comments_counter || 0 %>, Likes: <%= post.likes_counter || 0 %></p>
        </div>

      <% end %>
    </div>
    <div class="btn-container">
      <%= link_to 'Go Back', users_path, class: 'posts-btn black-border' %>
      <%= link_to 'See all posts', user_posts_path(user_id: @user.id), class: 'posts-btn black-border' %>
    </div>
  </div>
</body>

</html>