config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', passwords: 'users/passwords'}
  root to: 'users#index'

  devise_scope :user do 
    get '/users/sign_out', to: 'users/sessions#destroy'
  end

  post '/api/v1/signup', to: 'api/v1/registrations#create'
  post '/api/v1/signin', to: 'api/v1/sessions#create'

  resources :posts, only: [:new, :create]
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :destroy] do
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create]
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show] do
        resources :posts, only: [:index, :show] do
          resources :comments, only: [:index, :show, :create]
        end
      end
    end
  end
end

# hello

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :author, class_name: 'User'
  has_many :likes, class_name: 'Like', dependent: :delete_all
  has_many :comments, class_name: 'Comment', dependent: :delete_all

  after_create :update_post_counter

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def update_post_counter
    author.increment!(:posts_counter)
  end

  def most_recent_comments
    comments.limit(5).order(created_at: :desc)
  end

  def reduced_text
    return text if text.length < 200

    "#{text[0, 200]}..."
  end

  def liked?(user)
    likes.each do |like|
      return true if like.author_id == user.id
    end
    false
  end

  private :update_post_counter
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    user = User.find(params[:user_id])
    render json: user.posts, status: :ok
  rescue StandardError => e
    render json: { error: e }, status: :ok
  end

  def show
    user = User.find(params[:user_id])
    post = user.posts.find(params[:id])
    render json: post, status: :ok
  rescue StandardError => e
    render json: { error: e }, status: :not_found
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :check_user
  load_and_authorize_resource

  def index
    @user = User.includes(:posts, posts: [:comments, { comments: [:author] }]).find(params[:user_id])
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.includes(:comments, comments: [:author]).find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    post = current_user.posts.new(post_params)
    if post.save
      redirect_to "/users/#{post.author.id}/posts/#{post.id}"
      flash[:success] = 'Post was created!'
    else
      redirect_to '/posts/new'
      flash[:error] = 'ERROR! Post was not created.'
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.author.update(posts_counter: post.author.posts_counter - 1)
    post.delete
    redirect_to root_path, notice: 'Post was deleted!'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/views/posts/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Blog App! - <%= @user.name %> posts</title>
</head>
<body>
  <div class="index">
    <% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: "#{name} generic-alert" %>
    <% end -%>

    <div class="user">
      <img class="user-image black-border" src='<%= @user.photo %>' alt="user-image">
      
      <div class="user-basic-data black-border">
        <%= link_to @user.name, user_path(id: @user.id), class: 'user-index-name' %>
          <p class="user-index-posts">Posts: <%= @user.posts_counter || 0 %></p>
      </div>
    </div>

    <div class="user-posts">
      <% @user.posts.each do |post| %>
        <div class="user-bio black-border">
          <%= link_to "#{post.title}", user_post_path(user_id: post.author.id, id: post.id), method: :get, class: 'section-title hover-title' %>
          <p><%= post.reduced_text %></p>
          <p class="post-com-like">Comments: <%= post.comments_counter || 0 %>, Likes: <%= post.likes_counter || 0 %></p>
          <% if can? :destroy, post %>
            <%= button_to "Delete post", user_post_path(user_id: post.author.id, id: post.id), method: :delete, data: {confirm: 'Are you sure? '} %>
          <% end %>
        </div>
        <ul class="post-comments black-border">
          <% post.most_recent_comments.each do |comment| %>
            <li class="comment"><b><%= comment.author.name %></b>: <%= comment.text %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
    <div class="btn-container">
      <%= link_to 'Go Back', user_path(id: @user.id), class: 'posts-btn black-border' %>
      <%= link_to 'Pagination', user_path(id: @user.id), class: 'posts-btn black-border' %>
    </div>
  </div>
</body>

</html>

app/views/posts/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Blog App! - Create a post</title>
</head>
<body>
  <% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: "#{name} generic-alert" %>
  <% end -%>
  <div class="index">
    <div class="">
      <h2>Create Post</h2>
    </div>
    <%= form_with model: @post , class: 'flex flex-column' do |f| %>
      <%= f.text_field :title, placeholder: 'Title' %>
      <%= f.text_area :text, placeholder: 'Write the post\'s content!', class: 'my-1' %>
      <%= f.submit "Submit", disable_with: 'Submiting...', class: 'submit-btn black-border' %>
    <% end %>
  </div>
  <div class="btn-container">
    <%= link_to 'Go Back', users_path, class: 'posts-btn black-border' %>
  </div>
</body>
</html>

app/views/posts/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Blog App!</title>
</head>
<body>
  <% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: "#{name} generic-alert" %>
  <% end -%>
  <div class="post black-border">
    <div class="post-detailed">
      <h3 class="section-title"><%= @post.title %> by <%= @user.name %></h3>
      <div class="flex">
        <p class="mx-1">Comments: <%= @post.comments_counter || 0 %>, Likes: <%= @post.likes_counter || 0 %></p>
        <%= form_with model: Like.new, url: user_post_likes_path(post_id: @post.id), method: :post, class: 'flex' do |f| %>
          <%= f.submit "Laik", class: 'submit-btn black-border' %>
        <% end %>
      </div>
    </div>
    <p><%= @post.text %></p>
    <% if can? :destroy, @post %>
      <%= button_to "Delete post", user_post_path(user_id: @post.author.id, id: @post.id), method: :delete, data: {confirm: 'Are you sure? '} %>
    <% end %>
  </div>
  <ul class="post-comments black-border comment-order">
    <% @post.comments.each do |comment| %>
      <div class="comment-row">
        <li class="comment"><b><%= comment.author.name %></b>: <%= comment.text %></li>
        <% if can? :destroy, comment %>
          <%= button_to "Delete comment", user_post_comment_path(user_id: comment.author.id, post_id: comment.post.id, id: comment.id), method: :delete, data: {confirm: 'Are you sure? '} %>
        <% end %>
      </div>
    <% end %>
  </ul>

  <div class="user-bio black-border">
    <h3 class="section-title">Add a Comment!</h3>
    <%= form_with model: Comment.new, url: user_post_comments_path(post_id: @post.id), method: :post, class: 'flex flex-column' do |f| %>
      <%= f.text_area :text, placeholder: 'Write a comment!', class: 'full-size my-1', style: 'resize: vertical;' %>
      <%= f.submit "Submit", disable_with: 'Submiting...', data_role: 'none', class: 'submit-btn black-border' %>
    <% end %>
  </div>

  <div class="btn-container">
    <%= link_to 'Go Back', user_posts_path(user_id: @post.author.id), class: 'posts-btn black-border' %>
  </div>
</body>
</html>